export const KLING_AVATARS = [
  {
    id: "ashley-1",
    name: "Ashley",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Ashley.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Ashley.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-ashley",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "isabella-2",
    name: "Isabella",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Isabella.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Isabella.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-isabella",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "lia-3",
    name: "Lia",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Lia.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Lia.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-lia",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "raj-4",
    name: "Raj",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Raj.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Raj.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-raj",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "arina-5",
    name: "Arina",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Arina.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Arina.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-arina",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "ethan-6",
    name: "Ethan",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Ethan.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Ethan.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-ethan",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "lucas-7",
    name: "Lucas",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Lucas.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Lucas.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-lucas",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "2dboy-8",
    name: "2DBoy",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/2DBoy.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/2DBoy.mp4",
    avatarType: "AI_GENERATED_BATCH_2",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "cartoon", "2d"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-2dboy",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "charlie-9",
    name: "Charlie",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Charlie.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Charlie.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-charlie",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "matt-10",
    name: "Matt",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Matt.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Matt.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-matt",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "luis-11",
    name: "Luis",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Luis.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Luis.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-luis",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "anna-12",
    name: "Anna",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Anna.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Anna.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-anna",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "kathy-13",
    name: "Kathy",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Kathy.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Kathy.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-kathy",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "joon-14",
    name: "Joon",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Joon.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Joon.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "casual", "asian"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-joon",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "david-15",
    name: "David",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/David.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/David.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-david",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "noah-16",
    name: "Noah",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Noah.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Noah.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-noah",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "amy-17",
    name: "Amy",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Amy.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Amy.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-amy",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "freya-18",
    name: "Freya",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Freya.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Freya.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-freya",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "sophie-19",
    name: "Sophie",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Sophie.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Sophie.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-sophie",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "odette-20",
    name: "Odette",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Odette.jpg",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Odette.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-odette",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "darius-21",
    name: "Darius",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Darius.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Darius.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-darius",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "fay-22",
    name: "Fay",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Fay.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Fay.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-fay",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "daniel-23",
    name: "Daniel",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Daniel.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Daniel.mp4",
    avatarType: "LIFELIKE",
    gender: "male",
    orientation: "portrait",
    tags: ["male", "professional"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-daniel",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "petra-24",
    name: "Petra",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Petra.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Petra.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-petra",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "runa-25",
    name: "Runa",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Runa.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Runa.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual", "asian"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-runa",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "3d-26",
    name: "3D",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/3D.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/3D.mp4",
    avatarType: "FLAGSHIP",
    gender: "unknown",
    orientation: "portrait",
    tags: ["3d", "character"],
    isPremium: true,
    quality: "high",
    voiceId: "voice-3d",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "funcharacters-27",
    name: "Fun Characters",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Fun Characters.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Fun Characters.mp4",
    avatarType: "UGC",
    gender: "unknown",
    orientation: "portrait",
    tags: ["fun", "group", "cartoon"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-generic",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
  {
    id: "yumi-28",
    name: "Yumi",
    imageUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Yumi.png",
    videoUrl:
      "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/video/Yumi.mp4",
    avatarType: "LIFELIKE",
    gender: "female",
    orientation: "portrait",
    tags: ["female", "casual", "asian"],
    isPremium: false,
    quality: "medium",
    voiceId: "voice-yumi",
    numLooks: 1,
    createdAt: 1704067200000,
    debugScore: 0.5,
  },
];
