export const carouselItems = [
  {
    id: 1,
    href: "/pricing",
    title: "Pro Plan Special",
    subtitle: "Get 50% more credits with annual subscription",
    bgColor: "linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 50%, #16213e 100%)",
    accentColor: "#74ff52",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Ashley.png",
  },
  {
    id: 2,
    href: "/tools/image-generator",
    title: "AI Image Generation",
    subtitle: "Create stunning images with FLUX, Ideogram & more",
    bgColor: "linear-gradient(135deg, #1a1a2e 0%, #2d1b69 50%, #11998e 100%)",
    accentColor: "#74ff52",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Isabella.png",
  },
  {
    id: 3,
    href: "/tools/video-generator",
    title: "AI Video Generation",
    subtitle: "Transform ideas into cinematic videos with Kling, Luma & Runway",
    bgColor: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    accentColor: "#a855f7",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Ethan.png",
  },
  {
    id: 4,
    href: "/audio",
    title: "AI Voice & Audio",
    subtitle: "Generate realistic voiceovers with ElevenLabs technology",
    bgColor: "linear-gradient(135deg, #141e30 0%, #243b55 50%, #0f2027 100%)",
    accentColor: "#38bdf8",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Lia.png",
  },
  {
    id: 5,
    href: "/templates",
    title: "Ready-to-Use Templates",
    subtitle: "Jumpstart your creativity with curated AI templates",
    bgColor: "linear-gradient(135deg, #1f1c2c 0%, #928dab 30%, #1f1c2c 100%)",
    accentColor: "#f472b6",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Sophie.png",
  },
  {
    id: 6,
    href: "/explore",
    title: "Explore Gallery",
    subtitle: "Discover amazing AI-generated content from the community",
    bgColor: "linear-gradient(135deg, #0d1117 0%, #161b22 50%, #0d1117 100%)",
    accentColor: "#fbbf24",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Lucas.png",
  },
  {
    id: 7,
    href: "/tools/avatar-video",
    title: "AI Avatar Videos",
    subtitle: "Create talking avatar videos with realistic AI presenters",
    bgColor: "linear-gradient(135deg, #1a1a2e 0%, #4a1942 50%, #1a1a2e 100%)",
    accentColor: "#ec4899",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Amy.png",
  },
  {
    id: 8,
    href: "/assets",
    title: "Your Assets Library",
    subtitle: "Manage all your AI-generated creations in one place",
    bgColor: "linear-gradient(135deg, #0a0a0a 0%, #1e3a5f 50%, #0a0a0a 100%)",
    accentColor: "#22d3ee",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/David.png",
  },
];

export const sideBanner = {
  href: "/tools/image-to-video",
  title: "Image to Video",
  subtitle: "Animate your images with AI magic",
  bgColor: "linear-gradient(135deg, #0f0f23 0%, #1a1a40 50%, #2d1b4e 100%)",
  accentColor: "#74ff52",
  frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Freya.png",
};

export const actionItems = [
  {
    id: 1,
    title: "New: Video Effects",
    desc: "Apply stunning AI effects to transform your videos instantly",
    href: "/tools/video-effects",
    bgColor: "linear-gradient(135deg, #1a1a2e 0%, #2d1b69 100%)",
    accentColor: "#a855f7",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Raj.png",
  },
  {
    id: 2,
    title: "AI Lip Sync",
    desc: "Sync any face to audio with realistic mouth movements",
    href: "/tools/lip-sync",
    bgColor: "linear-gradient(135deg, #0d1117 0%, #1e3a5f 100%)",
    accentColor: "#38bdf8",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Anna.png",
  },
  {
    id: 3,
    title: "Background Removal",
    desc: "Remove backgrounds from images with one click",
    href: "/tools/background-removal",
    bgColor: "linear-gradient(135deg, #141414 0%, #2a4a3e 100%)",
    accentColor: "#74ff52",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Joon.png",
  },
  {
    id: 4,
    title: "Getting Started Guide",
    desc: "Learn tips & tricks to master Hexwave.ai tools",
    href: "/explore",
    bgColor: "linear-gradient(135deg, #1a1a2e 0%, #3d2b5a 100%)",
    accentColor: "#fbbf24",
    frontImage: "https://s16-def.ap4r.com/bs2/upload-ylab-stunt-sgp/kling/digital/image/Yumi.png",
  },
];
